# Generated by Django 5.1.6 on 2025-03-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_student_id_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
