# Generated by Django 5.1.7 on 2025-04-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
