# Generated by Django 5.1.7 on 2025-04-06 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteens', '0004_canteen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canteen',
            options={'verbose_name': 'Canteen', 'verbose_name_plural': 'Canteens'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='canteen',
            name='staff',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_canteen': True}, related_name='canteen_staff', to=settings.AUTH_USER_MODEL, verbose_name='Canteen Staff'),
        ),
        migrations.AddField(
            model_name='category',
            name='canteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='canteens.canteen', verbose_name='Canteen'),
        ),
        migrations.AddField(
            model_name='menu',
            name='canteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='canteens.canteen', verbose_name='Canteen'),
        ),
        migrations.AddField(
            model_name='student',
            name='canteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='canteens.canteen', verbose_name='Assigned Canteen'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='canteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='canteens.canteen', verbose_name='Canteen'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_canteen': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_canteens', to=settings.AUTH_USER_MODEL, verbose_name='Canteen Manager'),
        ),
        migrations.AlterField(
            model_name='canteen',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_parent': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Student User'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='canteens.menu', verbose_name='Menu Item'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='processed_by',
            field=models.ForeignKey(limit_choices_to={'is_canteen': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Processed By'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='canteens.student', verbose_name='Student'),
        ),
    ]
